version: "3"
services:
    backend:
        build: ./backend
        expose:
            - ${APP_BACKEND_PORT}
        environment:
            APP_BACKEND_PORT: ${APP_BACKEND_PORT}
        ports:
            - ${APP_BACKEND_PORT}:${APP_BACKEND_PORT}
        volumes:
            - ./backend/src:/usr/src/weatherapp/backend/src
        command: npm run dev

    frontend:
        build: ./frontend
        expose:
            - ${APP_FRONTEND_PORT}
        environment:
            APP_CLIENT_PORT: ${APP_FRONTEND_PORT}
        ports:
            - ${APP_FRONTEND_PORT}:${APP_FRONTEND_PORT}
        volumes:
            - ./frontend/src:/usr/src/weatherapp/frontend/src
        links:
            - backend
        command: npm start
