version: "3"
services:
    backend:
        build: ./backend
        expose:
            - ${BACKEND_PORT}
        environment:
            PORT: ${BACKEND_PORT}
            APPID: ${APPID}
            MAP_ENDPOINT: ${MAP_ENDPOINT}
            TARGET_CITY: ${TARGET_CITY}
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        volumes:
            - ./backend/src:/usr/src/weatherapp/backend/src
        command: npm run dev

    frontend:
        build: ./frontend
        expose:
            - ${FRONTEND_PORT}
        environment:
            HOST: ${FRONTEND_HOST}
            PORT: ${FRONTEND_PORT}
            ENDPOINT: ${ENDPOINT}
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        volumes:
            - ./frontend/src:/usr/src/weatherapp/frontend/src
        links:
            - backend
        command: npm start
