version: "3"
services:
    wiremock:
        build: ./wiremock
        ports:
            - "8080:8080"
        volumes:
            - ./wiremock:/home/wiremock
        
    backend:
        build: ../../backend
        environment:
            PORT: ${BACKEND_PORT}
            APPID: ${APPID}
            MAP_ENDPOINT: ${MAP_ENDPOINT}
            DEFAULT_CITY: ${DEFAULT_CITY}
            DEFAULT_COUNTRY: ${DEFAULT_COUNTRY}
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        volumes:
            - ../../backend/src:/usr/src/weatherapp/backend/src
        links:
            - wiremock
        command: npm run dev

    frontend:
        build: ../../frontend
        environment:
            HOST: ${FRONTEND_HOST}
            PORT: ${FRONTEND_HOST}
            ENDPOINT: ${BACKEND_ENDPOINT}
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        volumes:
            - ../../frontend/src:/usr/src/weatherapp/frontend/src
        links:
            - wiremock
        command: npm start

    robotframework:
        build: .
        volumes:
            - ./tests:/usr/src/robot-framework/tests
        depends_on:
            - frontend
        command: robot tests/
        # TODO implement waiting for frontend server to start - e.g. bash script with curl
        # currently infinite restarts
        restart: on-failure
